version: '3'
services: 
    database:
        image: "postgres"
        restart: always
        env_file: 
            - ".env"
        ports:
            - 5432:5432
        volumes: 
            - "database_data:/val/lib/postgres_sql/data/"
volumes: 
    database_data: